### ISSUE TITLE
Android has a sad

### ISSUE THREAD

**Issue by carlwiedemann** [sarahjschultz/kittengif#2]
mp4 video don't work. Gonna try that webp game. But we probably need Modernizr. And detection is async.

**Comment by sarahjschultz** [comment]
Alternate concept: Put up a flash that tells people to GET WITH THE PICTURE and get an iPhone.
![dealwitit](https://cloud.githubusercontent.com/assets/1680359/20190692/b96bdae0-a73f-11e6-889f-768ac6ff9ae3.gif)

**Comment by carlwiedemann** [comment]
![b64c34ad5aa9f47883a7cb48a8ccc8d4](https://cloud.githubusercontent.com/assets/350855/20190969/cc9a8b42-a740-11e6-8468-af34a1cfa17e.jpg)

**Comment by carlwiedemann** [comment]
Fixed in f6f1f772a6d54140a4f25b880bc3560534328d19
