### ISSUE TITLE
A nameless ghost broke frontpage style

### ISSUE THREAD

**Issue by sarahjschultz** [sarahjschultz/kittengif#4]
### SUMMARY:
Orange you glad I let you touch my CSS?
![screen shot 2016-11-11 at 2 54 17 pm](https://cloud.githubusercontent.com/assets/1680359/20231404/d0c188b8-a81e-11e6-8870-6a492af3a3bd.png)

`about` should not be orange.

**Comment by sarahjschultz** [comment]
Have a fix for this. Pushing up shortly.

**Comment by carlwiedemann** [comment]
👻  💻
