### ISSUE TITLE
Static site generation

### ISSUE THREAD

**Issue by carlwiedemann** [sarahjschultz/kittengif#6]
In light of https://github.com/sarahjschultz/kittengif/issues/5 I was thinking an alternative means of deployment would be to have a script that would statically generate "index.html" & Giphy data from a script rather than editing these directly.

We could do this in Ruby, or anything else -- maybe Python for a different flavor.

**Comment by sarahjschultz** [comment]
Alternatively, let's rewrite the page as a React component and deploy as a single page app.

**Comment by carlwiedemann** [comment]
That is probably more hipster and I/we would learn more. Will create new issue.
